# Set Version parameter
{% set version = "2.33.0" %}
package:
  name: eccodes
  # When updating, consider updating chaquopy-lame as well.
  version: "{{ version }}"
build:
    number: 0
source:
  url: https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.33.0-Source.tar.gz

requirements:

  build:
    - cmake 3.28.3
  host: 
    - libaec 1.1.2

